apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: etape2
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etape2-replica
        tier: frontend
    spec:
      containers:
      - name: app-redis
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-etape4
spec:
  selector:
    app.kubernetes.io/name: etape2-replica
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080